# Generated by Django 2.2 on 2020-01-11 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='Email',
            new_name='username',
        ),
    ]
